<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/11
 * Time: 17:28
 */
namespace app\api\controller;

use app\common\controller\Api;
use app\api\controller\Cc;

class TimerTask extends Api
{
    protected $noNeedLogin = '*';
    protected $noNeedRight = '*';

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $host = $this->get_server_host();
        $server_ip = gethostbyname($host);
        $cip = $this->get_remote_ip();

        if($cip != $server_ip){
            die("ip:".$cip." Permission denied");
        }
//        setCc()
    }

    /**
     * 发放加速奖
     */
    public function actJ(){
        $bonus = new Bonus();
        $bonus->actJsj();
    }

    /**
     * 打开App
     */
    public function openA(){
        $is_auto = config('site.is_auto');
        if (!$is_auto){
            return 123;
        }

        $start = config('site.opentime')['开放时间'];
        $start = strtotime(date('Y-m-d '.$start, time()));

        $end = config('site.opentime')['关闭时间'];
        $end = strtotime(date('Y-m-d '.$end, time()));

        $now = time();
        if ($now<$start || $now>=$end){
            $value = 0;
        }else{
            $value = 1;
        }

        $dbvalue = db('config')->field('value')->where("name='app_status'")->find();
        if ($dbvalue != $value){
            $res = db('config')->where("name='app_status'")->update(['value'=>$value]);
            return $res;
        }else{
            return 'abc';
        }

    }

    /**
     * 交易订单付款后2小时后，卖家自动确认
     */
    public function confirmOrder(){
        //状态为3待确认，paytime超过两个小时，自动确认
        $pretime = strtotime("-2 hours");

        $orders = db('cc_order')->where("state=3")->where("paytime<={$pretime}")->select();

        $cc = new Cc();
        foreach ($orders as $order){
            $user = db('user')->field('id')->where("username='{$order['uuname']}'")->find();
            $param = array('uid'=>$user['id'], 'orderid'=>$order['id']);
            $cc->dealOrder($param, false);
        }
    }


    //获取服务器域名
    private function get_server_host() {
        return isset($_SERVER['HTTP_X_FORWARDED_HOST']) ? $_SERVER['HTTP_X_FORWARDED_HOST'] : (isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : '');
    }

    //获取访问的ip
    private function get_remote_ip() {
        return isset($_SERVER["HTTP_X_FORWARDED_FOR"])?$_SERVER["HTTP_X_FORWARDED_FOR"]
            :(isset($_SERVER["HTTP_CLIENT_IP"])?$_SERVER["HTTP_CLIENT_IP"]
                :$_SERVER["REMOTE_ADDR"]);
    }

}